// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function AddToDo(props) {
  var onAdd = props.onAdd;
  var inputValueRef = React.useRef(undefined);
  var onSubmit = function (e) {
    e.preventDefault();
    onAdd(inputValueRef.current);
  };
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsx("input", {
                      className: "border rounded-l-lg bg-slate-50  h-8 text-xl py-6 px-4 ring-sky-200 col-span-10  focus:(outline-none border-sky-400 ring-2 z-10) ",
                      required: true,
                      onChange: (function (e) {
                          var target = e.target;
                          inputValueRef.current = target.value;
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "add",
                      className: "bg-white border rounded-r-lg cursor-pointer flex border-l-0 text-lg ring-sky-400 col-span-2 items-center justify-center hover:(bg-slate-100) focus:(ring-2 bg-slate-50) ",
                      type: "submit"
                    })
              ],
              className: "rounded-lg w-full grid px-6 grid-cols-12 my-3",
              onSubmit: onSubmit
            });
}

var make = AddToDo;

export {
  make ,
}
/* react Not a pure module */
