// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ToDoItem(props) {
  var todo = props.todo;
  var completed = todo.completed;
  var id = todo.id;
  var onRemove = props.onRemove;
  var onToggle = props.onToggle;
  return JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx("input", {
                      className: "h-6 m-0 mr-4 w-6 accent-sky-600",
                      checked: completed,
                      type: "checkbox",
                      onChange: (function (param) {
                          onToggle(id);
                        })
                    }),
                JsxRuntime.jsx("span", {
                      children: todo.text,
                      className: "-mt-1 break-words max-w-[350px] " + (
                        completed ? "text-gray-500 line-through" : "text-black"
                      )
                    }),
                JsxRuntime.jsx("button", {
                      children: "delete",
                      className: "bg-transparent cursor-pointer ml-auto h-6 p-0 w-6 hover:text-rose-600",
                      onClick: (function (param) {
                          onRemove(id);
                        })
                    })
              ],
              className: "border-b flex py-4 px-6 text-3xl items-center"
            });
}

var make = ToDoItem;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
