// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ToDoItem from "./ToDoItem.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function ToDoList(props) {
  var onDispatch = props.onDispatch;
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx("ul", {
                        children: Belt_Array.map(props.todos, (function (todo) {
                                return JsxRuntime.jsx(ToDoItem.make, {
                                            todo: todo,
                                            onToggle: (function (id) {
                                                onDispatch({
                                                      TAG: "ToggleTodo",
                                                      _0: id
                                                    });
                                              }),
                                            onRemove: (function (id) {
                                                onDispatch({
                                                      TAG: "RemoveTodo",
                                                      _0: id
                                                    });
                                              })
                                          }, todo.id.toString());
                              })),
                        className: "border-t list-none py-0 px-0"
                      }))
            });
}

var make = ToDoList;

export {
  make ,
}
/* ToDoItem Not a pure module */
